import Navbar from '@/containers/Navbar'
import './globals.css'
import SideBar from '@/containers/SideBar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-zinc-950 max-h-fit '>
           {children}
      </body>
    </html>
  )
}
